package app.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_classroom", "id", Classroom.class);
		arp.addMapping("t_college", "id", College.class);
		arp.addMapping("t_course", "id", Course.class);
		arp.addMapping("t_elecource", "id", Elecource.class);
		arp.addMapping("t_major", "id", Major.class);
		arp.addMapping("t_permission", "id", Permission.class);
		arp.addMapping("t_role", "id", Role.class);
		arp.addMapping("t_rolepermission", "id", Rolepermission.class);
		arp.addMapping("t_student", "id", Student.class);
		arp.addMapping("t_teacher", "id", Teacher.class);
		arp.addMapping("t_user", "id", User.class);
	}
}

