package app.model;

import app.model.base.BaseAutoSignInTableList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AutoSignInTableList extends BaseAutoSignInTableList<AutoSignInTableList> {
	public static final AutoSignInTableList dao = new AutoSignInTableList().dao();
}
