package app.model;

import app.model.base.BaseClassroom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classroom extends BaseClassroom<Classroom> {
	public static final Classroom dao = new Classroom().dao();
}
