package app.model;

import app.model.base.BaseCollege;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class College extends BaseCollege<College> {
	public static final College dao = new College().dao();
}
