package app.model;

import app.model.base.BaseElecourse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Elecourse extends BaseElecourse<Elecourse> {
	public static final Elecourse dao = new Elecourse().dao();
}
