package app.model;

import app.model.base.BaseElecource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Elecource extends BaseElecource<Elecource> {
	public static final Elecource dao = new Elecource().dao();
}
