package app.model;

import app.model.base.BaseRolepermission;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rolepermission extends BaseRolepermission<Rolepermission> {
	public static final Rolepermission dao = new Rolepermission().dao();
}
