package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePermission<M extends BasePermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setUri(java.lang.String uri) {
		set("uri", uri);
		return (M)this;
	}

	public java.lang.String getUri() {
		return get("uri");
	}

	public M setIsMenu(byte[] isMenu) {
		set("isMenu", isMenu);
		return (M)this;
	}

	public byte[] getIsMenu() {
		return get("isMenu");
	}

	public M setIsPage(byte[] isPage) {
		set("isPage", isPage);
		return (M)this;
	}

	public byte[] getIsPage() {
		return get("isPage");
	}

	public M setIsAction(byte[] isAction) {
		set("isAction", isAction);
		return (M)this;
	}

	public byte[] getIsAction() {
		return get("isAction");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setCreateBy(java.lang.Integer createBy) {
		set("createBy", createBy);
		return (M)this;
	}

	public java.lang.Integer getCreateBy() {
		return get("createBy");
	}

}
