package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCollege<M extends BaseCollege<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setStudentCount(java.lang.Integer studentCount) {
		set("studentCount", studentCount);
		return (M)this;
	}

	public java.lang.Integer getStudentCount() {
		return get("studentCount");
	}

	public M setTeacherCount(java.lang.Integer teacherCount) {
		set("teacherCount", teacherCount);
		return (M)this;
	}

	public java.lang.Integer getTeacherCount() {
		return get("teacherCount");
	}

}
