package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRolepermission<M extends BaseRolepermission<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setRoleId(java.lang.Integer roleId) {
		set("roleId", roleId);
		return (M)this;
	}

	public java.lang.Integer getRoleId() {
		return get("roleId");
	}

	public M setPerId(java.lang.Integer perId) {
		set("perId", perId);
		return (M)this;
	}

	public java.lang.Integer getPerId() {
		return get("perId");
	}

	public M setAuthorizedBy(java.lang.Integer authorizedBy) {
		set("authorizedBy", authorizedBy);
		return (M)this;
	}

	public java.lang.Integer getAuthorizedBy() {
		return get("authorizedBy");
	}

}
