package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setEntranceYear(java.lang.Integer entranceYear) {
		set("entranceYear", entranceYear);
		return (M)this;
	}

	public java.lang.Integer getEntranceYear() {
		return get("entranceYear");
	}

	public M setEntranceTime(java.util.Date entranceTime) {
		set("entranceTime", entranceTime);
		return (M)this;
	}

	public java.util.Date getEntranceTime() {
		return get("entranceTime");
	}

	public M setCollegeId(java.lang.Integer collegeId) {
		set("collegeId", collegeId);
		return (M)this;
	}

	public java.lang.Integer getCollegeId() {
		return get("collegeId");
	}

	public M setMajorId(java.lang.Integer majorId) {
		set("majorId", majorId);
		return (M)this;
	}

	public java.lang.Integer getMajorId() {
		return get("majorId");
	}

	public M setInClassId(java.lang.Integer inClassId) {
		set("inClassId", inClassId);
		return (M)this;
	}

	public java.lang.Integer getInClassId() {
		return get("inClassId");
	}

}
