package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCollegeId(java.lang.Integer collegeId) {
		set("collegeId", collegeId);
		return (M)this;
	}

	public java.lang.Integer getCollegeId() {
		return get("collegeId");
	}

	public M setProTitle(java.lang.String proTitle) {
		set("proTitle", proTitle);
		return (M)this;
	}

	public java.lang.String getProTitle() {
		return get("proTitle");
	}

}
