package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCourse<M extends BaseCourse<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setStudentCount(java.lang.Integer studentCount) {
		set("studentCount", studentCount);
		return (M)this;
	}

	public java.lang.Integer getStudentCount() {
		return get("studentCount");
	}

	public M setTeacherId(java.lang.Integer teacherId) {
		set("teacherId", teacherId);
		return (M)this;
	}

	public java.lang.Integer getTeacherId() {
		return get("teacherId");
	}

	public M setRoomId(java.lang.Integer roomId) {
		set("roomId", roomId);
		return (M)this;
	}

	public java.lang.Integer getRoomId() {
		return get("roomId");
	}

	public M setWeek(java.lang.Integer week) {
		set("week", week);
		return (M)this;
	}

	public java.lang.Integer getWeek() {
		return get("week");
	}

	public M setPartStart(java.lang.Integer partStart) {
		set("partStart", partStart);
		return (M)this;
	}

	public java.lang.Integer getPartStart() {
		return get("partStart");
	}

	public M setPartEnd(java.lang.Integer partEnd) {
		set("partEnd", partEnd);
		return (M)this;
	}

	public java.lang.Integer getPartEnd() {
		return get("partEnd");
	}

}
