package app.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseElecource<M extends BaseElecource<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setStudentId(java.lang.Integer studentId) {
		set("studentId", studentId);
		return (M)this;
	}

	public java.lang.Integer getStudentId() {
		return get("studentId");
	}

	public M setCourseId(java.lang.Integer courseId) {
		set("courseId", courseId);
		return (M)this;
	}

	public java.lang.Integer getCourseId() {
		return get("courseId");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

}
